import "./globals.css";
import { Roboto, Cambo, Roboto_Slab } from "next/font/google";
import { Header, Footer } from "./components";
import { MenuContextProvider } from "./context/menu.context";

const roboto = Roboto({
  subsets: ["latin"],
  weight: "300",
  variable: "--font-roboto",
});
const cambo = Roboto_Slab({
  subsets: ["latin"],
  weight: "300",
  variable: "--font-cambo",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${roboto.variable} ${cambo.variable}`}>
        <MenuContextProvider>
          <Header />
        </MenuContextProvider>

        {children}
        <Footer />
      </body>
    </html>
  );
}
